/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WomenEmpowermentRouteImport } from './routes/women-empowerment'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as RdCellRouteImport } from './routes/rd-cell'
import { Route as ProfessionalBodiesRouteImport } from './routes/professional-bodies'
import { Route as PlacementsRouteImport } from './routes/placements'
import { Route as OtherAmenitiesRouteImport } from './routes/other-amenities'
import { Route as NssRouteImport } from './routes/nss'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as HostelsRouteImport } from './routes/hostels'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EngineeringCellRouteImport } from './routes/engineering-cell'
import { Route as DispensaryRouteImport } from './routes/dispensary'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CanteenRouteImport } from './routes/canteen'
import { Route as CampusLifeRouteImport } from './routes/campus-life'
import { Route as BankingRouteImport } from './routes/banking'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RdCellIndexRouteImport } from './routes/rd-cell.index'
import { Route as PlacementsIndexRouteImport } from './routes/placements.index'
import { Route as DispensaryIndexRouteImport } from './routes/dispensary.index'
import { Route as CampusLifeIndexRouteImport } from './routes/campus-life.index'
import { Route as AcademicsIndexRouteImport } from './routes/academics.index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as RdCellScholarsRouteImport } from './routes/rd-cell.scholars'
import { Route as RdCellPublicationsRouteImport } from './routes/rd-cell.publications'
import { Route as RdCellProjectsRouteImport } from './routes/rd-cell.projects'
import { Route as RdCellMousRouteImport } from './routes/rd-cell.mous'
import { Route as RdCellAreasRouteImport } from './routes/rd-cell.areas'
import { Route as RdCellAboutRouteImport } from './routes/rd-cell.about'
import { Route as PlacementsTrainingRouteImport } from './routes/placements.training'
import { Route as PlacementsStudentsRouteImport } from './routes/placements.students'
import { Route as PlacementsRecruitersRouteImport } from './routes/placements.recruiters'
import { Route as PlacementsGalleryRouteImport } from './routes/placements.gallery'
import { Route as OtherAmenitiesStaffQuartersRouteImport } from './routes/other-amenities.staff-quarters'
import { Route as OtherAmenitiesGuestHouseRouteImport } from './routes/other-amenities.guest-house'
import { Route as CampusLifeStudentActivityClubRouteImport } from './routes/campus-life.student-activity-club'
import { Route as CampusLifeMusicClubRouteImport } from './routes/campus-life.music-club'
import { Route as AdministrationVicePrincipalRouteImport } from './routes/administration.vice-principal'
import { Route as AdministrationPrincipalsOfficeRouteImport } from './routes/administration.principals-office'
import { Route as AdministrationPrincipalRouteImport } from './routes/administration.principal'
import { Route as AdministrationIqacRouteImport } from './routes/administration.iqac'
import { Route as AdminSportsRouteImport } from './routes/admin/sports'
import { Route as AdminPlacementsRouteImport } from './routes/admin.placements'
import { Route as AdminLibraryRouteImport } from './routes/admin/library'
import { Route as AdminEngineeringCellRouteImport } from './routes/admin/engineering-cell'
import { Route as AdminDispensaryRouteImport } from './routes/admin/dispensary'
import { Route as AcademicsTimeTablesRouteImport } from './routes/academics.time-tables'
import { Route as AcademicsSyllabusRouteImport } from './routes/academics.syllabus'
import { Route as AcademicsScholarshipsRouteImport } from './routes/academics.scholarships'
import { Route as AcademicsRegulationsRouteImport } from './routes/academics.regulations'
import { Route as AcademicsProgramsRouteImport } from './routes/academics.programs'
import { Route as AcademicsDownloadsRouteImport } from './routes/academics.downloads'
import { Route as AcademicsCacRouteImport } from './routes/academics.cac'
import { Route as AcademicsAdmissionsRouteImport } from './routes/academics.admissions'
import { Route as AboutVizianagaramRouteImport } from './routes/about.vizianagaram'
import { Route as AboutVisionMissionRouteImport } from './routes/about.vision-mission'
import { Route as AboutJntukRouteImport } from './routes/about.jntuk'
import { Route as AboutInstitutionRouteImport } from './routes/about.institution'
import { Route as AboutHowToReachRouteImport } from './routes/about.how-to-reach'
import { Route as AdministrationIqacIndexRouteImport } from './routes/administration.iqac.index'
import { Route as AdministrationIqacMousRouteImport } from './routes/administration.iqac.mous'
import { Route as AdministrationIqacMeetingsRouteImport } from './routes/administration.iqac.meetings'
import { Route as AdministrationIqacCompositionRouteImport } from './routes/administration.iqac.composition'
import { Route as AdministrationIqacAqarRouteImport } from './routes/administration.iqac.aqar'

const WomenEmpowermentRoute = WomenEmpowermentRouteImport.update({
  id: '/women-empowerment',
  path: '/women-empowerment',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const RdCellRoute = RdCellRouteImport.update({
  id: '/rd-cell',
  path: '/rd-cell',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalBodiesRoute = ProfessionalBodiesRouteImport.update({
  id: '/professional-bodies',
  path: '/professional-bodies',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementsRoute = PlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => rootRouteImport,
} as any)
const OtherAmenitiesRoute = OtherAmenitiesRouteImport.update({
  id: '/other-amenities',
  path: '/other-amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const NssRoute = NssRouteImport.update({
  id: '/nss',
  path: '/nss',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const HostelsRoute = HostelsRouteImport.update({
  id: '/hostels',
  path: '/hostels',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineeringCellRoute = EngineeringCellRouteImport.update({
  id: '/engineering-cell',
  path: '/engineering-cell',
  getParentRoute: () => rootRouteImport,
} as any)
const DispensaryRoute = DispensaryRouteImport.update({
  id: '/dispensary',
  path: '/dispensary',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CanteenRoute = CanteenRouteImport.update({
  id: '/canteen',
  path: '/canteen',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusLifeRoute = CampusLifeRouteImport.update({
  id: '/campus-life',
  path: '/campus-life',
  getParentRoute: () => rootRouteImport,
} as any)
const BankingRoute = BankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RdCellIndexRoute = RdCellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RdCellRoute,
} as any)
const PlacementsIndexRoute = PlacementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlacementsRoute,
} as any)
const DispensaryIndexRoute = DispensaryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DispensaryRoute,
} as any)
const CampusLifeIndexRoute = CampusLifeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampusLifeRoute,
} as any)
const AcademicsIndexRoute = AcademicsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademicsRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const RdCellScholarsRoute = RdCellScholarsRouteImport.update({
  id: '/scholars',
  path: '/scholars',
  getParentRoute: () => RdCellRoute,
} as any)
const RdCellPublicationsRoute = RdCellPublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => RdCellRoute,
} as any)
const RdCellProjectsRoute = RdCellProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => RdCellRoute,
} as any)
const RdCellMousRoute = RdCellMousRouteImport.update({
  id: '/mous',
  path: '/mous',
  getParentRoute: () => RdCellRoute,
} as any)
const RdCellAreasRoute = RdCellAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => RdCellRoute,
} as any)
const RdCellAboutRoute = RdCellAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => RdCellRoute,
} as any)
const PlacementsTrainingRoute = PlacementsTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => PlacementsRoute,
} as any)
const PlacementsStudentsRoute = PlacementsStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => PlacementsRoute,
} as any)
const PlacementsRecruitersRoute = PlacementsRecruitersRouteImport.update({
  id: '/recruiters',
  path: '/recruiters',
  getParentRoute: () => PlacementsRoute,
} as any)
const PlacementsGalleryRoute = PlacementsGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => PlacementsRoute,
} as any)
const OtherAmenitiesStaffQuartersRoute =
  OtherAmenitiesStaffQuartersRouteImport.update({
    id: '/staff-quarters',
    path: '/staff-quarters',
    getParentRoute: () => OtherAmenitiesRoute,
  } as any)
const OtherAmenitiesGuestHouseRoute =
  OtherAmenitiesGuestHouseRouteImport.update({
    id: '/guest-house',
    path: '/guest-house',
    getParentRoute: () => OtherAmenitiesRoute,
  } as any)
const CampusLifeStudentActivityClubRoute =
  CampusLifeStudentActivityClubRouteImport.update({
    id: '/student-activity-club',
    path: '/student-activity-club',
    getParentRoute: () => CampusLifeRoute,
  } as any)
const CampusLifeMusicClubRoute = CampusLifeMusicClubRouteImport.update({
  id: '/music-club',
  path: '/music-club',
  getParentRoute: () => CampusLifeRoute,
} as any)
const AdministrationVicePrincipalRoute =
  AdministrationVicePrincipalRouteImport.update({
    id: '/vice-principal',
    path: '/vice-principal',
    getParentRoute: () => AdministrationRoute,
  } as any)
const AdministrationPrincipalsOfficeRoute =
  AdministrationPrincipalsOfficeRouteImport.update({
    id: '/principals-office',
    path: '/principals-office',
    getParentRoute: () => AdministrationRoute,
  } as any)
const AdministrationPrincipalRoute = AdministrationPrincipalRouteImport.update({
  id: '/principal',
  path: '/principal',
  getParentRoute: () => AdministrationRoute,
} as any)
const AdministrationIqacRoute = AdministrationIqacRouteImport.update({
  id: '/iqac',
  path: '/iqac',
  getParentRoute: () => AdministrationRoute,
} as any)
const AdminSportsRoute = AdminSportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlacementsRoute = AdminPlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLibraryRoute = AdminLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEngineeringCellRoute = AdminEngineeringCellRouteImport.update({
  id: '/engineering-cell',
  path: '/engineering-cell',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDispensaryRoute = AdminDispensaryRouteImport.update({
  id: '/dispensary',
  path: '/dispensary',
  getParentRoute: () => AdminRoute,
} as any)
const AcademicsTimeTablesRoute = AcademicsTimeTablesRouteImport.update({
  id: '/time-tables',
  path: '/time-tables',
  getParentRoute: () => AcademicsRoute,
} as any)
const AcademicsSyllabusRoute = AcademicsSyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => AcademicsRoute,
} as any)
const AcademicsScholarshipsRoute = AcademicsScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => AcademicsRoute,
} as any)
const AcademicsRegulationsRoute = AcademicsRegulationsRouteImport.update({
  id: '/regulations',
  path: '/regulations',
  getParentRoute: () => AcademicsRoute,
} as any)
const AcademicsProgramsRoute = AcademicsProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AcademicsRoute,
} as any)
const AcademicsDownloadsRoute = AcademicsDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AcademicsRoute,
} as any)
const AcademicsCacRoute = AcademicsCacRouteImport.update({
  id: '/cac',
  path: '/cac',
  getParentRoute: () => AcademicsRoute,
} as any)
const AcademicsAdmissionsRoute = AcademicsAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AcademicsRoute,
} as any)
const AboutVizianagaramRoute = AboutVizianagaramRouteImport.update({
  id: '/vizianagaram',
  path: '/vizianagaram',
  getParentRoute: () => AboutRoute,
} as any)
const AboutVisionMissionRoute = AboutVisionMissionRouteImport.update({
  id: '/vision-mission',
  path: '/vision-mission',
  getParentRoute: () => AboutRoute,
} as any)
const AboutJntukRoute = AboutJntukRouteImport.update({
  id: '/jntuk',
  path: '/jntuk',
  getParentRoute: () => AboutRoute,
} as any)
const AboutInstitutionRoute = AboutInstitutionRouteImport.update({
  id: '/institution',
  path: '/institution',
  getParentRoute: () => AboutRoute,
} as any)
const AboutHowToReachRoute = AboutHowToReachRouteImport.update({
  id: '/how-to-reach',
  path: '/how-to-reach',
  getParentRoute: () => AboutRoute,
} as any)
const AdministrationIqacIndexRoute = AdministrationIqacIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdministrationIqacRoute,
} as any)
const AdministrationIqacMousRoute = AdministrationIqacMousRouteImport.update({
  id: '/mous',
  path: '/mous',
  getParentRoute: () => AdministrationIqacRoute,
} as any)
const AdministrationIqacMeetingsRoute =
  AdministrationIqacMeetingsRouteImport.update({
    id: '/meetings',
    path: '/meetings',
    getParentRoute: () => AdministrationIqacRoute,
  } as any)
const AdministrationIqacCompositionRoute =
  AdministrationIqacCompositionRouteImport.update({
    id: '/composition',
    path: '/composition',
    getParentRoute: () => AdministrationIqacRoute,
  } as any)
const AdministrationIqacAqarRoute = AdministrationIqacAqarRouteImport.update({
  id: '/aqar',
  path: '/aqar',
  getParentRoute: () => AdministrationIqacRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/academics': typeof AcademicsRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/administration': typeof AdministrationRouteWithChildren
  '/admissions': typeof AdmissionsRoute
  '/banking': typeof BankingRoute
  '/campus-life': typeof CampusLifeRouteWithChildren
  '/canteen': typeof CanteenRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/dispensary': typeof DispensaryRouteWithChildren
  '/engineering-cell': typeof EngineeringCellRoute
  '/gallery': typeof GalleryRoute
  '/hostels': typeof HostelsRoute
  '/library': typeof LibraryRoute
  '/notices': typeof NoticesRoute
  '/nss': typeof NssRoute
  '/other-amenities': typeof OtherAmenitiesRouteWithChildren
  '/placements': typeof PlacementsRouteWithChildren
  '/professional-bodies': typeof ProfessionalBodiesRoute
  '/rd-cell': typeof RdCellRouteWithChildren
  '/sports': typeof SportsRoute
  '/women-empowerment': typeof WomenEmpowermentRoute
  '/about/how-to-reach': typeof AboutHowToReachRoute
  '/about/institution': typeof AboutInstitutionRoute
  '/about/jntuk': typeof AboutJntukRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/about/vizianagaram': typeof AboutVizianagaramRoute
  '/academics/admissions': typeof AcademicsAdmissionsRoute
  '/academics/cac': typeof AcademicsCacRoute
  '/academics/downloads': typeof AcademicsDownloadsRoute
  '/academics/programs': typeof AcademicsProgramsRoute
  '/academics/regulations': typeof AcademicsRegulationsRoute
  '/academics/scholarships': typeof AcademicsScholarshipsRoute
  '/academics/syllabus': typeof AcademicsSyllabusRoute
  '/academics/time-tables': typeof AcademicsTimeTablesRoute
  '/admin/dispensary': typeof AdminDispensaryRoute
  '/admin/engineering-cell': typeof AdminEngineeringCellRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/placements': typeof AdminPlacementsRoute
  '/admin/sports': typeof AdminSportsRoute
  '/administration/iqac': typeof AdministrationIqacRouteWithChildren
  '/administration/principal': typeof AdministrationPrincipalRoute
  '/administration/principals-office': typeof AdministrationPrincipalsOfficeRoute
  '/administration/vice-principal': typeof AdministrationVicePrincipalRoute
  '/campus-life/music-club': typeof CampusLifeMusicClubRoute
  '/campus-life/student-activity-club': typeof CampusLifeStudentActivityClubRoute
  '/other-amenities/guest-house': typeof OtherAmenitiesGuestHouseRoute
  '/other-amenities/staff-quarters': typeof OtherAmenitiesStaffQuartersRoute
  '/placements/gallery': typeof PlacementsGalleryRoute
  '/placements/recruiters': typeof PlacementsRecruitersRoute
  '/placements/students': typeof PlacementsStudentsRoute
  '/placements/training': typeof PlacementsTrainingRoute
  '/rd-cell/about': typeof RdCellAboutRoute
  '/rd-cell/areas': typeof RdCellAreasRoute
  '/rd-cell/mous': typeof RdCellMousRoute
  '/rd-cell/projects': typeof RdCellProjectsRoute
  '/rd-cell/publications': typeof RdCellPublicationsRoute
  '/rd-cell/scholars': typeof RdCellScholarsRoute
  '/about/': typeof AboutIndexRoute
  '/academics/': typeof AcademicsIndexRoute
  '/campus-life/': typeof CampusLifeIndexRoute
  '/dispensary/': typeof DispensaryIndexRoute
  '/placements/': typeof PlacementsIndexRoute
  '/rd-cell/': typeof RdCellIndexRoute
  '/administration/iqac/aqar': typeof AdministrationIqacAqarRoute
  '/administration/iqac/composition': typeof AdministrationIqacCompositionRoute
  '/administration/iqac/meetings': typeof AdministrationIqacMeetingsRoute
  '/administration/iqac/mous': typeof AdministrationIqacMousRoute
  '/administration/iqac/': typeof AdministrationIqacIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/administration': typeof AdministrationRouteWithChildren
  '/admissions': typeof AdmissionsRoute
  '/banking': typeof BankingRoute
  '/canteen': typeof CanteenRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/engineering-cell': typeof EngineeringCellRoute
  '/gallery': typeof GalleryRoute
  '/hostels': typeof HostelsRoute
  '/library': typeof LibraryRoute
  '/notices': typeof NoticesRoute
  '/nss': typeof NssRoute
  '/other-amenities': typeof OtherAmenitiesRouteWithChildren
  '/professional-bodies': typeof ProfessionalBodiesRoute
  '/sports': typeof SportsRoute
  '/women-empowerment': typeof WomenEmpowermentRoute
  '/about/how-to-reach': typeof AboutHowToReachRoute
  '/about/institution': typeof AboutInstitutionRoute
  '/about/jntuk': typeof AboutJntukRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/about/vizianagaram': typeof AboutVizianagaramRoute
  '/academics/admissions': typeof AcademicsAdmissionsRoute
  '/academics/cac': typeof AcademicsCacRoute
  '/academics/downloads': typeof AcademicsDownloadsRoute
  '/academics/programs': typeof AcademicsProgramsRoute
  '/academics/regulations': typeof AcademicsRegulationsRoute
  '/academics/scholarships': typeof AcademicsScholarshipsRoute
  '/academics/syllabus': typeof AcademicsSyllabusRoute
  '/academics/time-tables': typeof AcademicsTimeTablesRoute
  '/admin/dispensary': typeof AdminDispensaryRoute
  '/admin/engineering-cell': typeof AdminEngineeringCellRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/placements': typeof AdminPlacementsRoute
  '/admin/sports': typeof AdminSportsRoute
  '/administration/principal': typeof AdministrationPrincipalRoute
  '/administration/principals-office': typeof AdministrationPrincipalsOfficeRoute
  '/administration/vice-principal': typeof AdministrationVicePrincipalRoute
  '/campus-life/music-club': typeof CampusLifeMusicClubRoute
  '/campus-life/student-activity-club': typeof CampusLifeStudentActivityClubRoute
  '/other-amenities/guest-house': typeof OtherAmenitiesGuestHouseRoute
  '/other-amenities/staff-quarters': typeof OtherAmenitiesStaffQuartersRoute
  '/placements/gallery': typeof PlacementsGalleryRoute
  '/placements/recruiters': typeof PlacementsRecruitersRoute
  '/placements/students': typeof PlacementsStudentsRoute
  '/placements/training': typeof PlacementsTrainingRoute
  '/rd-cell/about': typeof RdCellAboutRoute
  '/rd-cell/areas': typeof RdCellAreasRoute
  '/rd-cell/mous': typeof RdCellMousRoute
  '/rd-cell/projects': typeof RdCellProjectsRoute
  '/rd-cell/publications': typeof RdCellPublicationsRoute
  '/rd-cell/scholars': typeof RdCellScholarsRoute
  '/about': typeof AboutIndexRoute
  '/academics': typeof AcademicsIndexRoute
  '/campus-life': typeof CampusLifeIndexRoute
  '/dispensary': typeof DispensaryIndexRoute
  '/placements': typeof PlacementsIndexRoute
  '/rd-cell': typeof RdCellIndexRoute
  '/administration/iqac/aqar': typeof AdministrationIqacAqarRoute
  '/administration/iqac/composition': typeof AdministrationIqacCompositionRoute
  '/administration/iqac/meetings': typeof AdministrationIqacMeetingsRoute
  '/administration/iqac/mous': typeof AdministrationIqacMousRoute
  '/administration/iqac': typeof AdministrationIqacIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/academics': typeof AcademicsRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/administration': typeof AdministrationRouteWithChildren
  '/admissions': typeof AdmissionsRoute
  '/banking': typeof BankingRoute
  '/campus-life': typeof CampusLifeRouteWithChildren
  '/canteen': typeof CanteenRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/dispensary': typeof DispensaryRouteWithChildren
  '/engineering-cell': typeof EngineeringCellRoute
  '/gallery': typeof GalleryRoute
  '/hostels': typeof HostelsRoute
  '/library': typeof LibraryRoute
  '/notices': typeof NoticesRoute
  '/nss': typeof NssRoute
  '/other-amenities': typeof OtherAmenitiesRouteWithChildren
  '/placements': typeof PlacementsRouteWithChildren
  '/professional-bodies': typeof ProfessionalBodiesRoute
  '/rd-cell': typeof RdCellRouteWithChildren
  '/sports': typeof SportsRoute
  '/women-empowerment': typeof WomenEmpowermentRoute
  '/about/how-to-reach': typeof AboutHowToReachRoute
  '/about/institution': typeof AboutInstitutionRoute
  '/about/jntuk': typeof AboutJntukRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/about/vizianagaram': typeof AboutVizianagaramRoute
  '/academics/admissions': typeof AcademicsAdmissionsRoute
  '/academics/cac': typeof AcademicsCacRoute
  '/academics/downloads': typeof AcademicsDownloadsRoute
  '/academics/programs': typeof AcademicsProgramsRoute
  '/academics/regulations': typeof AcademicsRegulationsRoute
  '/academics/scholarships': typeof AcademicsScholarshipsRoute
  '/academics/syllabus': typeof AcademicsSyllabusRoute
  '/academics/time-tables': typeof AcademicsTimeTablesRoute
  '/admin/dispensary': typeof AdminDispensaryRoute
  '/admin/engineering-cell': typeof AdminEngineeringCellRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/placements': typeof AdminPlacementsRoute
  '/admin/sports': typeof AdminSportsRoute
  '/administration/iqac': typeof AdministrationIqacRouteWithChildren
  '/administration/principal': typeof AdministrationPrincipalRoute
  '/administration/principals-office': typeof AdministrationPrincipalsOfficeRoute
  '/administration/vice-principal': typeof AdministrationVicePrincipalRoute
  '/campus-life/music-club': typeof CampusLifeMusicClubRoute
  '/campus-life/student-activity-club': typeof CampusLifeStudentActivityClubRoute
  '/other-amenities/guest-house': typeof OtherAmenitiesGuestHouseRoute
  '/other-amenities/staff-quarters': typeof OtherAmenitiesStaffQuartersRoute
  '/placements/gallery': typeof PlacementsGalleryRoute
  '/placements/recruiters': typeof PlacementsRecruitersRoute
  '/placements/students': typeof PlacementsStudentsRoute
  '/placements/training': typeof PlacementsTrainingRoute
  '/rd-cell/about': typeof RdCellAboutRoute
  '/rd-cell/areas': typeof RdCellAreasRoute
  '/rd-cell/mous': typeof RdCellMousRoute
  '/rd-cell/projects': typeof RdCellProjectsRoute
  '/rd-cell/publications': typeof RdCellPublicationsRoute
  '/rd-cell/scholars': typeof RdCellScholarsRoute
  '/about/': typeof AboutIndexRoute
  '/academics/': typeof AcademicsIndexRoute
  '/campus-life/': typeof CampusLifeIndexRoute
  '/dispensary/': typeof DispensaryIndexRoute
  '/placements/': typeof PlacementsIndexRoute
  '/rd-cell/': typeof RdCellIndexRoute
  '/administration/iqac/aqar': typeof AdministrationIqacAqarRoute
  '/administration/iqac/composition': typeof AdministrationIqacCompositionRoute
  '/administration/iqac/meetings': typeof AdministrationIqacMeetingsRoute
  '/administration/iqac/mous': typeof AdministrationIqacMousRoute
  '/administration/iqac/': typeof AdministrationIqacIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academics'
    | '/admin'
    | '/administration'
    | '/admissions'
    | '/banking'
    | '/campus-life'
    | '/canteen'
    | '/contact'
    | '/departments'
    | '/dispensary'
    | '/engineering-cell'
    | '/gallery'
    | '/hostels'
    | '/library'
    | '/notices'
    | '/nss'
    | '/other-amenities'
    | '/placements'
    | '/professional-bodies'
    | '/rd-cell'
    | '/sports'
    | '/women-empowerment'
    | '/about/how-to-reach'
    | '/about/institution'
    | '/about/jntuk'
    | '/about/vision-mission'
    | '/about/vizianagaram'
    | '/academics/admissions'
    | '/academics/cac'
    | '/academics/downloads'
    | '/academics/programs'
    | '/academics/regulations'
    | '/academics/scholarships'
    | '/academics/syllabus'
    | '/academics/time-tables'
    | '/admin/dispensary'
    | '/admin/engineering-cell'
    | '/admin/library'
    | '/admin/placements'
    | '/admin/sports'
    | '/administration/iqac'
    | '/administration/principal'
    | '/administration/principals-office'
    | '/administration/vice-principal'
    | '/campus-life/music-club'
    | '/campus-life/student-activity-club'
    | '/other-amenities/guest-house'
    | '/other-amenities/staff-quarters'
    | '/placements/gallery'
    | '/placements/recruiters'
    | '/placements/students'
    | '/placements/training'
    | '/rd-cell/about'
    | '/rd-cell/areas'
    | '/rd-cell/mous'
    | '/rd-cell/projects'
    | '/rd-cell/publications'
    | '/rd-cell/scholars'
    | '/about/'
    | '/academics/'
    | '/campus-life/'
    | '/dispensary/'
    | '/placements/'
    | '/rd-cell/'
    | '/administration/iqac/aqar'
    | '/administration/iqac/composition'
    | '/administration/iqac/meetings'
    | '/administration/iqac/mous'
    | '/administration/iqac/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/administration'
    | '/admissions'
    | '/banking'
    | '/canteen'
    | '/contact'
    | '/departments'
    | '/engineering-cell'
    | '/gallery'
    | '/hostels'
    | '/library'
    | '/notices'
    | '/nss'
    | '/other-amenities'
    | '/professional-bodies'
    | '/sports'
    | '/women-empowerment'
    | '/about/how-to-reach'
    | '/about/institution'
    | '/about/jntuk'
    | '/about/vision-mission'
    | '/about/vizianagaram'
    | '/academics/admissions'
    | '/academics/cac'
    | '/academics/downloads'
    | '/academics/programs'
    | '/academics/regulations'
    | '/academics/scholarships'
    | '/academics/syllabus'
    | '/academics/time-tables'
    | '/admin/dispensary'
    | '/admin/engineering-cell'
    | '/admin/library'
    | '/admin/placements'
    | '/admin/sports'
    | '/administration/principal'
    | '/administration/principals-office'
    | '/administration/vice-principal'
    | '/campus-life/music-club'
    | '/campus-life/student-activity-club'
    | '/other-amenities/guest-house'
    | '/other-amenities/staff-quarters'
    | '/placements/gallery'
    | '/placements/recruiters'
    | '/placements/students'
    | '/placements/training'
    | '/rd-cell/about'
    | '/rd-cell/areas'
    | '/rd-cell/mous'
    | '/rd-cell/projects'
    | '/rd-cell/publications'
    | '/rd-cell/scholars'
    | '/about'
    | '/academics'
    | '/campus-life'
    | '/dispensary'
    | '/placements'
    | '/rd-cell'
    | '/administration/iqac/aqar'
    | '/administration/iqac/composition'
    | '/administration/iqac/meetings'
    | '/administration/iqac/mous'
    | '/administration/iqac'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academics'
    | '/admin'
    | '/administration'
    | '/admissions'
    | '/banking'
    | '/campus-life'
    | '/canteen'
    | '/contact'
    | '/departments'
    | '/dispensary'
    | '/engineering-cell'
    | '/gallery'
    | '/hostels'
    | '/library'
    | '/notices'
    | '/nss'
    | '/other-amenities'
    | '/placements'
    | '/professional-bodies'
    | '/rd-cell'
    | '/sports'
    | '/women-empowerment'
    | '/about/how-to-reach'
    | '/about/institution'
    | '/about/jntuk'
    | '/about/vision-mission'
    | '/about/vizianagaram'
    | '/academics/admissions'
    | '/academics/cac'
    | '/academics/downloads'
    | '/academics/programs'
    | '/academics/regulations'
    | '/academics/scholarships'
    | '/academics/syllabus'
    | '/academics/time-tables'
    | '/admin/dispensary'
    | '/admin/engineering-cell'
    | '/admin/library'
    | '/admin/placements'
    | '/admin/sports'
    | '/administration/iqac'
    | '/administration/principal'
    | '/administration/principals-office'
    | '/administration/vice-principal'
    | '/campus-life/music-club'
    | '/campus-life/student-activity-club'
    | '/other-amenities/guest-house'
    | '/other-amenities/staff-quarters'
    | '/placements/gallery'
    | '/placements/recruiters'
    | '/placements/students'
    | '/placements/training'
    | '/rd-cell/about'
    | '/rd-cell/areas'
    | '/rd-cell/mous'
    | '/rd-cell/projects'
    | '/rd-cell/publications'
    | '/rd-cell/scholars'
    | '/about/'
    | '/academics/'
    | '/campus-life/'
    | '/dispensary/'
    | '/placements/'
    | '/rd-cell/'
    | '/administration/iqac/aqar'
    | '/administration/iqac/composition'
    | '/administration/iqac/meetings'
    | '/administration/iqac/mous'
    | '/administration/iqac/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  AcademicsRoute: typeof AcademicsRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AdministrationRoute: typeof AdministrationRouteWithChildren
  AdmissionsRoute: typeof AdmissionsRoute
  BankingRoute: typeof BankingRoute
  CampusLifeRoute: typeof CampusLifeRouteWithChildren
  CanteenRoute: typeof CanteenRoute
  ContactRoute: typeof ContactRoute
  DepartmentsRoute: typeof DepartmentsRoute
  DispensaryRoute: typeof DispensaryRouteWithChildren
  EngineeringCellRoute: typeof EngineeringCellRoute
  GalleryRoute: typeof GalleryRoute
  HostelsRoute: typeof HostelsRoute
  LibraryRoute: typeof LibraryRoute
  NoticesRoute: typeof NoticesRoute
  NssRoute: typeof NssRoute
  OtherAmenitiesRoute: typeof OtherAmenitiesRouteWithChildren
  PlacementsRoute: typeof PlacementsRouteWithChildren
  ProfessionalBodiesRoute: typeof ProfessionalBodiesRoute
  RdCellRoute: typeof RdCellRouteWithChildren
  SportsRoute: typeof SportsRoute
  WomenEmpowermentRoute: typeof WomenEmpowermentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/women-empowerment': {
      id: '/women-empowerment'
      path: '/women-empowerment'
      fullPath: '/women-empowerment'
      preLoaderRoute: typeof WomenEmpowermentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rd-cell': {
      id: '/rd-cell'
      path: '/rd-cell'
      fullPath: '/rd-cell'
      preLoaderRoute: typeof RdCellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional-bodies': {
      id: '/professional-bodies'
      path: '/professional-bodies'
      fullPath: '/professional-bodies'
      preLoaderRoute: typeof ProfessionalBodiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placements': {
      id: '/placements'
      path: '/placements'
      fullPath: '/placements'
      preLoaderRoute: typeof PlacementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/other-amenities': {
      id: '/other-amenities'
      path: '/other-amenities'
      fullPath: '/other-amenities'
      preLoaderRoute: typeof OtherAmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nss': {
      id: '/nss'
      path: '/nss'
      fullPath: '/nss'
      preLoaderRoute: typeof NssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostels': {
      id: '/hostels'
      path: '/hostels'
      fullPath: '/hostels'
      preLoaderRoute: typeof HostelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering-cell': {
      id: '/engineering-cell'
      path: '/engineering-cell'
      fullPath: '/engineering-cell'
      preLoaderRoute: typeof EngineeringCellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispensary': {
      id: '/dispensary'
      path: '/dispensary'
      fullPath: '/dispensary'
      preLoaderRoute: typeof DispensaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canteen': {
      id: '/canteen'
      path: '/canteen'
      fullPath: '/canteen'
      preLoaderRoute: typeof CanteenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-life': {
      id: '/campus-life'
      path: '/campus-life'
      fullPath: '/campus-life'
      preLoaderRoute: typeof CampusLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banking': {
      id: '/banking'
      path: '/banking'
      fullPath: '/banking'
      preLoaderRoute: typeof BankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rd-cell/': {
      id: '/rd-cell/'
      path: '/'
      fullPath: '/rd-cell/'
      preLoaderRoute: typeof RdCellIndexRouteImport
      parentRoute: typeof RdCellRoute
    }
    '/placements/': {
      id: '/placements/'
      path: '/'
      fullPath: '/placements/'
      preLoaderRoute: typeof PlacementsIndexRouteImport
      parentRoute: typeof PlacementsRoute
    }
    '/dispensary/': {
      id: '/dispensary/'
      path: '/'
      fullPath: '/dispensary/'
      preLoaderRoute: typeof DispensaryIndexRouteImport
      parentRoute: typeof DispensaryRoute
    }
    '/campus-life/': {
      id: '/campus-life/'
      path: '/'
      fullPath: '/campus-life/'
      preLoaderRoute: typeof CampusLifeIndexRouteImport
      parentRoute: typeof CampusLifeRoute
    }
    '/academics/': {
      id: '/academics/'
      path: '/'
      fullPath: '/academics/'
      preLoaderRoute: typeof AcademicsIndexRouteImport
      parentRoute: typeof AcademicsRoute
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/rd-cell/scholars': {
      id: '/rd-cell/scholars'
      path: '/scholars'
      fullPath: '/rd-cell/scholars'
      preLoaderRoute: typeof RdCellScholarsRouteImport
      parentRoute: typeof RdCellRoute
    }
    '/rd-cell/publications': {
      id: '/rd-cell/publications'
      path: '/publications'
      fullPath: '/rd-cell/publications'
      preLoaderRoute: typeof RdCellPublicationsRouteImport
      parentRoute: typeof RdCellRoute
    }
    '/rd-cell/projects': {
      id: '/rd-cell/projects'
      path: '/projects'
      fullPath: '/rd-cell/projects'
      preLoaderRoute: typeof RdCellProjectsRouteImport
      parentRoute: typeof RdCellRoute
    }
    '/rd-cell/mous': {
      id: '/rd-cell/mous'
      path: '/mous'
      fullPath: '/rd-cell/mous'
      preLoaderRoute: typeof RdCellMousRouteImport
      parentRoute: typeof RdCellRoute
    }
    '/rd-cell/areas': {
      id: '/rd-cell/areas'
      path: '/areas'
      fullPath: '/rd-cell/areas'
      preLoaderRoute: typeof RdCellAreasRouteImport
      parentRoute: typeof RdCellRoute
    }
    '/rd-cell/about': {
      id: '/rd-cell/about'
      path: '/about'
      fullPath: '/rd-cell/about'
      preLoaderRoute: typeof RdCellAboutRouteImport
      parentRoute: typeof RdCellRoute
    }
    '/placements/training': {
      id: '/placements/training'
      path: '/training'
      fullPath: '/placements/training'
      preLoaderRoute: typeof PlacementsTrainingRouteImport
      parentRoute: typeof PlacementsRoute
    }
    '/placements/students': {
      id: '/placements/students'
      path: '/students'
      fullPath: '/placements/students'
      preLoaderRoute: typeof PlacementsStudentsRouteImport
      parentRoute: typeof PlacementsRoute
    }
    '/placements/recruiters': {
      id: '/placements/recruiters'
      path: '/recruiters'
      fullPath: '/placements/recruiters'
      preLoaderRoute: typeof PlacementsRecruitersRouteImport
      parentRoute: typeof PlacementsRoute
    }
    '/placements/gallery': {
      id: '/placements/gallery'
      path: '/gallery'
      fullPath: '/placements/gallery'
      preLoaderRoute: typeof PlacementsGalleryRouteImport
      parentRoute: typeof PlacementsRoute
    }
    '/other-amenities/staff-quarters': {
      id: '/other-amenities/staff-quarters'
      path: '/staff-quarters'
      fullPath: '/other-amenities/staff-quarters'
      preLoaderRoute: typeof OtherAmenitiesStaffQuartersRouteImport
      parentRoute: typeof OtherAmenitiesRoute
    }
    '/other-amenities/guest-house': {
      id: '/other-amenities/guest-house'
      path: '/guest-house'
      fullPath: '/other-amenities/guest-house'
      preLoaderRoute: typeof OtherAmenitiesGuestHouseRouteImport
      parentRoute: typeof OtherAmenitiesRoute
    }
    '/campus-life/student-activity-club': {
      id: '/campus-life/student-activity-club'
      path: '/student-activity-club'
      fullPath: '/campus-life/student-activity-club'
      preLoaderRoute: typeof CampusLifeStudentActivityClubRouteImport
      parentRoute: typeof CampusLifeRoute
    }
    '/campus-life/music-club': {
      id: '/campus-life/music-club'
      path: '/music-club'
      fullPath: '/campus-life/music-club'
      preLoaderRoute: typeof CampusLifeMusicClubRouteImport
      parentRoute: typeof CampusLifeRoute
    }
    '/administration/vice-principal': {
      id: '/administration/vice-principal'
      path: '/vice-principal'
      fullPath: '/administration/vice-principal'
      preLoaderRoute: typeof AdministrationVicePrincipalRouteImport
      parentRoute: typeof AdministrationRoute
    }
    '/administration/principals-office': {
      id: '/administration/principals-office'
      path: '/principals-office'
      fullPath: '/administration/principals-office'
      preLoaderRoute: typeof AdministrationPrincipalsOfficeRouteImport
      parentRoute: typeof AdministrationRoute
    }
    '/administration/principal': {
      id: '/administration/principal'
      path: '/principal'
      fullPath: '/administration/principal'
      preLoaderRoute: typeof AdministrationPrincipalRouteImport
      parentRoute: typeof AdministrationRoute
    }
    '/administration/iqac': {
      id: '/administration/iqac'
      path: '/iqac'
      fullPath: '/administration/iqac'
      preLoaderRoute: typeof AdministrationIqacRouteImport
      parentRoute: typeof AdministrationRoute
    }
    '/admin/sports': {
      id: '/admin/sports'
      path: '/sports'
      fullPath: '/admin/sports'
      preLoaderRoute: typeof AdminSportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/placements': {
      id: '/admin/placements'
      path: '/placements'
      fullPath: '/admin/placements'
      preLoaderRoute: typeof AdminPlacementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/library': {
      id: '/admin/library'
      path: '/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AdminLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/engineering-cell': {
      id: '/admin/engineering-cell'
      path: '/engineering-cell'
      fullPath: '/admin/engineering-cell'
      preLoaderRoute: typeof AdminEngineeringCellRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dispensary': {
      id: '/admin/dispensary'
      path: '/dispensary'
      fullPath: '/admin/dispensary'
      preLoaderRoute: typeof AdminDispensaryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/academics/time-tables': {
      id: '/academics/time-tables'
      path: '/time-tables'
      fullPath: '/academics/time-tables'
      preLoaderRoute: typeof AcademicsTimeTablesRouteImport
      parentRoute: typeof AcademicsRoute
    }
    '/academics/syllabus': {
      id: '/academics/syllabus'
      path: '/syllabus'
      fullPath: '/academics/syllabus'
      preLoaderRoute: typeof AcademicsSyllabusRouteImport
      parentRoute: typeof AcademicsRoute
    }
    '/academics/scholarships': {
      id: '/academics/scholarships'
      path: '/scholarships'
      fullPath: '/academics/scholarships'
      preLoaderRoute: typeof AcademicsScholarshipsRouteImport
      parentRoute: typeof AcademicsRoute
    }
    '/academics/regulations': {
      id: '/academics/regulations'
      path: '/regulations'
      fullPath: '/academics/regulations'
      preLoaderRoute: typeof AcademicsRegulationsRouteImport
      parentRoute: typeof AcademicsRoute
    }
    '/academics/programs': {
      id: '/academics/programs'
      path: '/programs'
      fullPath: '/academics/programs'
      preLoaderRoute: typeof AcademicsProgramsRouteImport
      parentRoute: typeof AcademicsRoute
    }
    '/academics/downloads': {
      id: '/academics/downloads'
      path: '/downloads'
      fullPath: '/academics/downloads'
      preLoaderRoute: typeof AcademicsDownloadsRouteImport
      parentRoute: typeof AcademicsRoute
    }
    '/academics/cac': {
      id: '/academics/cac'
      path: '/cac'
      fullPath: '/academics/cac'
      preLoaderRoute: typeof AcademicsCacRouteImport
      parentRoute: typeof AcademicsRoute
    }
    '/academics/admissions': {
      id: '/academics/admissions'
      path: '/admissions'
      fullPath: '/academics/admissions'
      preLoaderRoute: typeof AcademicsAdmissionsRouteImport
      parentRoute: typeof AcademicsRoute
    }
    '/about/vizianagaram': {
      id: '/about/vizianagaram'
      path: '/vizianagaram'
      fullPath: '/about/vizianagaram'
      preLoaderRoute: typeof AboutVizianagaramRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/vision-mission': {
      id: '/about/vision-mission'
      path: '/vision-mission'
      fullPath: '/about/vision-mission'
      preLoaderRoute: typeof AboutVisionMissionRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/jntuk': {
      id: '/about/jntuk'
      path: '/jntuk'
      fullPath: '/about/jntuk'
      preLoaderRoute: typeof AboutJntukRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/institution': {
      id: '/about/institution'
      path: '/institution'
      fullPath: '/about/institution'
      preLoaderRoute: typeof AboutInstitutionRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/how-to-reach': {
      id: '/about/how-to-reach'
      path: '/how-to-reach'
      fullPath: '/about/how-to-reach'
      preLoaderRoute: typeof AboutHowToReachRouteImport
      parentRoute: typeof AboutRoute
    }
    '/administration/iqac/': {
      id: '/administration/iqac/'
      path: '/'
      fullPath: '/administration/iqac/'
      preLoaderRoute: typeof AdministrationIqacIndexRouteImport
      parentRoute: typeof AdministrationIqacRoute
    }
    '/administration/iqac/mous': {
      id: '/administration/iqac/mous'
      path: '/mous'
      fullPath: '/administration/iqac/mous'
      preLoaderRoute: typeof AdministrationIqacMousRouteImport
      parentRoute: typeof AdministrationIqacRoute
    }
    '/administration/iqac/meetings': {
      id: '/administration/iqac/meetings'
      path: '/meetings'
      fullPath: '/administration/iqac/meetings'
      preLoaderRoute: typeof AdministrationIqacMeetingsRouteImport
      parentRoute: typeof AdministrationIqacRoute
    }
    '/administration/iqac/composition': {
      id: '/administration/iqac/composition'
      path: '/composition'
      fullPath: '/administration/iqac/composition'
      preLoaderRoute: typeof AdministrationIqacCompositionRouteImport
      parentRoute: typeof AdministrationIqacRoute
    }
    '/administration/iqac/aqar': {
      id: '/administration/iqac/aqar'
      path: '/aqar'
      fullPath: '/administration/iqac/aqar'
      preLoaderRoute: typeof AdministrationIqacAqarRouteImport
      parentRoute: typeof AdministrationIqacRoute
    }
  }
}

interface AboutRouteChildren {
  AboutHowToReachRoute: typeof AboutHowToReachRoute
  AboutInstitutionRoute: typeof AboutInstitutionRoute
  AboutJntukRoute: typeof AboutJntukRoute
  AboutVisionMissionRoute: typeof AboutVisionMissionRoute
  AboutVizianagaramRoute: typeof AboutVizianagaramRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutHowToReachRoute: AboutHowToReachRoute,
  AboutInstitutionRoute: AboutInstitutionRoute,
  AboutJntukRoute: AboutJntukRoute,
  AboutVisionMissionRoute: AboutVisionMissionRoute,
  AboutVizianagaramRoute: AboutVizianagaramRoute,
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface AcademicsRouteChildren {
  AcademicsAdmissionsRoute: typeof AcademicsAdmissionsRoute
  AcademicsCacRoute: typeof AcademicsCacRoute
  AcademicsDownloadsRoute: typeof AcademicsDownloadsRoute
  AcademicsProgramsRoute: typeof AcademicsProgramsRoute
  AcademicsRegulationsRoute: typeof AcademicsRegulationsRoute
  AcademicsScholarshipsRoute: typeof AcademicsScholarshipsRoute
  AcademicsSyllabusRoute: typeof AcademicsSyllabusRoute
  AcademicsTimeTablesRoute: typeof AcademicsTimeTablesRoute
  AcademicsIndexRoute: typeof AcademicsIndexRoute
}

const AcademicsRouteChildren: AcademicsRouteChildren = {
  AcademicsAdmissionsRoute: AcademicsAdmissionsRoute,
  AcademicsCacRoute: AcademicsCacRoute,
  AcademicsDownloadsRoute: AcademicsDownloadsRoute,
  AcademicsProgramsRoute: AcademicsProgramsRoute,
  AcademicsRegulationsRoute: AcademicsRegulationsRoute,
  AcademicsScholarshipsRoute: AcademicsScholarshipsRoute,
  AcademicsSyllabusRoute: AcademicsSyllabusRoute,
  AcademicsTimeTablesRoute: AcademicsTimeTablesRoute,
  AcademicsIndexRoute: AcademicsIndexRoute,
}

const AcademicsRouteWithChildren = AcademicsRoute._addFileChildren(
  AcademicsRouteChildren,
)

interface AdminRouteChildren {
  AdminDispensaryRoute: typeof AdminDispensaryRoute
  AdminEngineeringCellRoute: typeof AdminEngineeringCellRoute
  AdminLibraryRoute: typeof AdminLibraryRoute
  AdminPlacementsRoute: typeof AdminPlacementsRoute
  AdminSportsRoute: typeof AdminSportsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDispensaryRoute: AdminDispensaryRoute,
  AdminEngineeringCellRoute: AdminEngineeringCellRoute,
  AdminLibraryRoute: AdminLibraryRoute,
  AdminPlacementsRoute: AdminPlacementsRoute,
  AdminSportsRoute: AdminSportsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AdministrationIqacRouteChildren {
  AdministrationIqacAqarRoute: typeof AdministrationIqacAqarRoute
  AdministrationIqacCompositionRoute: typeof AdministrationIqacCompositionRoute
  AdministrationIqacMeetingsRoute: typeof AdministrationIqacMeetingsRoute
  AdministrationIqacMousRoute: typeof AdministrationIqacMousRoute
  AdministrationIqacIndexRoute: typeof AdministrationIqacIndexRoute
}

const AdministrationIqacRouteChildren: AdministrationIqacRouteChildren = {
  AdministrationIqacAqarRoute: AdministrationIqacAqarRoute,
  AdministrationIqacCompositionRoute: AdministrationIqacCompositionRoute,
  AdministrationIqacMeetingsRoute: AdministrationIqacMeetingsRoute,
  AdministrationIqacMousRoute: AdministrationIqacMousRoute,
  AdministrationIqacIndexRoute: AdministrationIqacIndexRoute,
}

const AdministrationIqacRouteWithChildren =
  AdministrationIqacRoute._addFileChildren(AdministrationIqacRouteChildren)

interface AdministrationRouteChildren {
  AdministrationIqacRoute: typeof AdministrationIqacRouteWithChildren
  AdministrationPrincipalRoute: typeof AdministrationPrincipalRoute
  AdministrationPrincipalsOfficeRoute: typeof AdministrationPrincipalsOfficeRoute
  AdministrationVicePrincipalRoute: typeof AdministrationVicePrincipalRoute
}

const AdministrationRouteChildren: AdministrationRouteChildren = {
  AdministrationIqacRoute: AdministrationIqacRouteWithChildren,
  AdministrationPrincipalRoute: AdministrationPrincipalRoute,
  AdministrationPrincipalsOfficeRoute: AdministrationPrincipalsOfficeRoute,
  AdministrationVicePrincipalRoute: AdministrationVicePrincipalRoute,
}

const AdministrationRouteWithChildren = AdministrationRoute._addFileChildren(
  AdministrationRouteChildren,
)

interface CampusLifeRouteChildren {
  CampusLifeMusicClubRoute: typeof CampusLifeMusicClubRoute
  CampusLifeStudentActivityClubRoute: typeof CampusLifeStudentActivityClubRoute
  CampusLifeIndexRoute: typeof CampusLifeIndexRoute
}

const CampusLifeRouteChildren: CampusLifeRouteChildren = {
  CampusLifeMusicClubRoute: CampusLifeMusicClubRoute,
  CampusLifeStudentActivityClubRoute: CampusLifeStudentActivityClubRoute,
  CampusLifeIndexRoute: CampusLifeIndexRoute,
}

const CampusLifeRouteWithChildren = CampusLifeRoute._addFileChildren(
  CampusLifeRouteChildren,
)

interface DispensaryRouteChildren {
  DispensaryIndexRoute: typeof DispensaryIndexRoute
}

const DispensaryRouteChildren: DispensaryRouteChildren = {
  DispensaryIndexRoute: DispensaryIndexRoute,
}

const DispensaryRouteWithChildren = DispensaryRoute._addFileChildren(
  DispensaryRouteChildren,
)

interface OtherAmenitiesRouteChildren {
  OtherAmenitiesGuestHouseRoute: typeof OtherAmenitiesGuestHouseRoute
  OtherAmenitiesStaffQuartersRoute: typeof OtherAmenitiesStaffQuartersRoute
}

const OtherAmenitiesRouteChildren: OtherAmenitiesRouteChildren = {
  OtherAmenitiesGuestHouseRoute: OtherAmenitiesGuestHouseRoute,
  OtherAmenitiesStaffQuartersRoute: OtherAmenitiesStaffQuartersRoute,
}

const OtherAmenitiesRouteWithChildren = OtherAmenitiesRoute._addFileChildren(
  OtherAmenitiesRouteChildren,
)

interface PlacementsRouteChildren {
  PlacementsGalleryRoute: typeof PlacementsGalleryRoute
  PlacementsRecruitersRoute: typeof PlacementsRecruitersRoute
  PlacementsStudentsRoute: typeof PlacementsStudentsRoute
  PlacementsTrainingRoute: typeof PlacementsTrainingRoute
  PlacementsIndexRoute: typeof PlacementsIndexRoute
}

const PlacementsRouteChildren: PlacementsRouteChildren = {
  PlacementsGalleryRoute: PlacementsGalleryRoute,
  PlacementsRecruitersRoute: PlacementsRecruitersRoute,
  PlacementsStudentsRoute: PlacementsStudentsRoute,
  PlacementsTrainingRoute: PlacementsTrainingRoute,
  PlacementsIndexRoute: PlacementsIndexRoute,
}

const PlacementsRouteWithChildren = PlacementsRoute._addFileChildren(
  PlacementsRouteChildren,
)

interface RdCellRouteChildren {
  RdCellAboutRoute: typeof RdCellAboutRoute
  RdCellAreasRoute: typeof RdCellAreasRoute
  RdCellMousRoute: typeof RdCellMousRoute
  RdCellProjectsRoute: typeof RdCellProjectsRoute
  RdCellPublicationsRoute: typeof RdCellPublicationsRoute
  RdCellScholarsRoute: typeof RdCellScholarsRoute
  RdCellIndexRoute: typeof RdCellIndexRoute
}

const RdCellRouteChildren: RdCellRouteChildren = {
  RdCellAboutRoute: RdCellAboutRoute,
  RdCellAreasRoute: RdCellAreasRoute,
  RdCellMousRoute: RdCellMousRoute,
  RdCellProjectsRoute: RdCellProjectsRoute,
  RdCellPublicationsRoute: RdCellPublicationsRoute,
  RdCellScholarsRoute: RdCellScholarsRoute,
  RdCellIndexRoute: RdCellIndexRoute,
}

const RdCellRouteWithChildren =
  RdCellRoute._addFileChildren(RdCellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  AcademicsRoute: AcademicsRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AdministrationRoute: AdministrationRouteWithChildren,
  AdmissionsRoute: AdmissionsRoute,
  BankingRoute: BankingRoute,
  CampusLifeRoute: CampusLifeRouteWithChildren,
  CanteenRoute: CanteenRoute,
  ContactRoute: ContactRoute,
  DepartmentsRoute: DepartmentsRoute,
  DispensaryRoute: DispensaryRouteWithChildren,
  EngineeringCellRoute: EngineeringCellRoute,
  GalleryRoute: GalleryRoute,
  HostelsRoute: HostelsRoute,
  LibraryRoute: LibraryRoute,
  NoticesRoute: NoticesRoute,
  NssRoute: NssRoute,
  OtherAmenitiesRoute: OtherAmenitiesRouteWithChildren,
  PlacementsRoute: PlacementsRouteWithChildren,
  ProfessionalBodiesRoute: ProfessionalBodiesRoute,
  RdCellRoute: RdCellRouteWithChildren,
  SportsRoute: SportsRoute,
  WomenEmpowermentRoute: WomenEmpowermentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
